//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public int Dispocitivo_ID { get; set; }
        public string Nombre { get; set; }
        public string Temperatura { get; set; }
        public System.DateTime FechaHora { get; set; }
    }
}
